version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: gestor_tareas_mongodb
    ports:
      - '27017:27017'  # mapea puerto local 27017 al contenedor
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

volumes:
  mongo_data:
